url: "https://iota-school.github.io/day_accessibility" # the base hostname & protocol for your site, e.g. http://example.com
root: /
baseurl: "/" # the subpath of your site, e.g. /blog
title: "STScI Day of Accessibility" # the name of your site, e.g. ACME Corp.


collections:
collections:
  projects:
    output: true
    order:
     - stsci.md
